kind: ConfigMap
apiVersion: v1
metadata:
  name: farms-legacy-config-#{ENV}#
  namespace: '#{NAMESPACE}#'
immutable: false
data:
  IMPORT_VIRUS_SCAN_DIR: '#{IMPORT_VIRUS_SCAN_DIR}#'
  IMPORT_STAGING_WINDOW_START: '#{IMPORT_STAGING_WINDOW_START}#'
  IMPORT_STAGING_WINDOW_END: '#{IMPORT_STAGING_WINDOW_END}#'
  IMPORT_IMPORT_WINDOW_START: '#{IMPORT_IMPORT_WINDOW_START}#'
  IMPORT_IMPORT_WINDOW_END: '#{IMPORT_IMPORT_WINDOW_END}#'
  IMPORT_TIMER_FREQUENCY: '#{IMPORT_TIMER_FREQUENCY}#'
  WEBAPP_FIRST_BC_ADMIN_YEAR: '#{WEBAPP_FIRST_BC_ADMIN_YEAR}#'
  WEBAPP_SIGN_OUT_URL: '#{WEBAPP_SIGN_OUT_URL}#'
  REPORTS_ORACLE_REPORTS_SERVER: '#{REPORTS_ORACLE_REPORTS_SERVER}#'
  ENROLMENT_START_YEAR: '#{ENROLMENT_START_YEAR}#'
  ENROLMENT_YEARS_AHEAD: '#{ENROLMENT_YEARS_AHEAD}#'
  BCEID_WEB_SERVICE_URL: '#{BCEID_WEB_SERVICE_URL}#'
  BCEID_ONLINE_SERVICE_ID: '#{BCEID_ONLINE_SERVICE_ID}#'
  BCEID_EXPIRY_PERIOD: '#{BCEID_EXPIRY_PERIOD}#'
  HELP_URL: '#{HELP_URL}#'
  HELP_FILE_PREFIX: '#{HELP_FILE_PREFIX}#'
  HELP_FILE_SUFFIX: '#{HELP_FILE_SUFFIX}#'
  WEBSERVICE_ALLOWABLE_IP_REGEX: '#{WEBSERVICE_ALLOWABLE_IP_REGEX}#'
  REPORTS_JAVA_REPORTS_SERVER: '#{REPORTS_JAVA_REPORTS_SERVER}#'
  IMPORT_BUSINESS_WINDOW_START: '#{IMPORT_BUSINESS_WINDOW_START}#'
  IMPORT_BUSINESS_WINDOW_END: '#{IMPORT_BUSINESS_WINDOW_END}#'
  CRM_ENROLMENT_FEE_MODIFIED_BY_USER_OVERRIDE: '#{CRM_ENROLMENT_FEE_MODIFIED_BY_USER_OVERRIDE}#'
  CRM_DYNAMICS_URL: '#{CRM_DYNAMICS_URL}#'
  CRM_API_VERSION: '#{CRM_API_VERSION}#'
  CRM_AUTHORITY_URL: '#{CRM_AUTHORITY_URL}#'
  CHEFS_AGENT_ENABLED: '#{CHEFS_AGENT_ENABLED}#'
  CHEFS_API_URL: '#{CHEFS_API_URL}#'
  CHEFS_API_VERSION: '#{CHEFS_API_VERSION}#'
  CHEFS_FORM_KEYS_NOL: '#{CHEFS_FORM_KEYS_NOL}#'
  FIFO_AGENT_ENABLED: '#{FIFO_AGENT_ENABLED}#'
  REPORTS_JASPER_REST_URL: '#{REPORTS_JASPER_REST_URL}#'
  REPORTS_JASPER_REPORTS_PATH: '#{REPORTS_JASPER_REPORTS_PATH}#'
